###
GET http://localhost:3001/SampleData1
###
POST http://localhost:3001/SampleData1 HTTP/1.1
Content-Type: application/json

{
    "s1item1": "plant",
    "s1item2": "pot",
    "s1item3": "water",
    "s1item4": "soil"
}
###
GET http://localhost:3001/SampleData2
###
POST http://localhost:3001/SampleData2 HTTP/1.1
Content-Type: application/json

{
    "s1item1": "dog",
    "s1item2": "cat",
    "s1item3": "bird",
    "s1item4": "snake"
}
